# Generated by Django 5.2 on 2025-05-07 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(help_text='请输入18位有效身份证号码，格式示例：31011520050101001X', max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='请输入有效的18位身份证号码', regex='^[1-9]\\d{5}(19|20)\\d{2}(0[1-9]|1[0-2])(0[1-9]|[12]\\d|3[01])\\d{3}[\\dXx]$')], verbose_name='身份证号码')),
                ('name', models.CharField(help_text='请输入学生真实姓名', max_length=50, verbose_name='学生姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], editable=False, help_text='根据身份证号第17位自动识别', max_length=1, verbose_name='性别')),
                ('birth_date', models.DateField(editable=False, help_text='根据身份证号第7-14位自动识别', verbose_name='出生日期')),
                ('grade', models.CharField(choices=[('1', '初一'), ('2', '初二'), ('3', '初三')], help_text='请选择当前就读年级', max_length=1, verbose_name='所在年级')),
                ('address', models.TextField(help_text='格式：省/市/区+街道+详细地址，示例：上海市浦东新区张江路123弄45号', max_length=200, verbose_name='家庭住址')),
                ('parent_name', models.CharField(help_text='请输入法定监护人姓名', max_length=50, verbose_name='监护人姓名')),
                ('parent_contact', models.CharField(help_text='请输入监护人手机号码，格式示例：13800138000', max_length=20, validators=[django.core.validators.RegexValidator(message='请输入有效的11位手机号码', regex='^1[3-9]\\d{9}$')], verbose_name='监护人联系方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录首次创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后修改时间', verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '学生档案',
                'verbose_name_plural': '学生档案',
                'indexes': [models.Index(fields=['id_card'], name='Students_st_id_card_56cf1a_idx'), models.Index(fields=['grade'], name='Students_st_grade_89fd37_idx')],
            },
        ),
    ]
