# Generated by Django 5.2 on 2025-05-07 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_at'], 'verbose_name': '学生档案', 'verbose_name_plural': '学生档案'},
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(help_text='示例：上海市浦东新区张江路123弄45号', verbose_name='家庭住址'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(editable=False, help_text='根据身份证号自动识别', verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], editable=False, help_text='根据身份证号自动识别', max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_card',
            field=models.CharField(help_text='请输入18位身份证号码，例如：31011520050101001X', max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='请输入有效的18位身份证号码', regex='^[1-9]\\d{5}(?:19|20)\\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\\d|3[01])\\d{3}[\\dXx]$')], verbose_name='身份证号码'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(help_text='学生真实姓名', max_length=50, verbose_name='学生姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_contact',
            field=models.CharField(help_text='例如：13800138000', max_length=11, validators=[django.core.validators.RegexValidator(message='请输入有效的11位手机号码', regex='^1[3-9]\\d{9}$')], verbose_name='监护人联系方式'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_name',
            field=models.CharField(help_text='法定监护人姓名', max_length=50, verbose_name='监护人姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
    ]
